# Generated by Django 5.0.6 on 2024-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('accModifier', models.CharField(choices=[('PUB', 'PUBLIC'), ('PRI', 'PRIVATE'), ('PRO', 'PROTECTED')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('postPic', models.ImageField(upload_to='postPictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
