# Generated by Django 5.0.6 on 2024-06-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootTitle', models.CharField(max_length=255)),
                ('bootAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='firstApp.author')),
            ],
        ),
    ]
