# Generated by Django 5.0.6 on 2024-06-07 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
