# Generated by Django 5.0.6 on 2024-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_userpost_slug_alter_teacher_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
