# Generated by Django 5.0.6 on 2024-06-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_author_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bootAuthor',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
