# Generated by Django 5.0.6 on 2024-06-01 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_teacher_rename_studname_student_studentname_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=255)),
                ('studentAge', models.IntegerField()),
                ('studentClass', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('studentSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.subject')),
            ],
        ),
    ]
