# Generated by Django 5.0.6 on 2024-06-09 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0002_alter_mentorprofile_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('course', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('father_name', models.CharField(max_length=255)),
                ('father_phone', models.IntegerField()),
                ('father_profession', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, upload_to='menteeProfilePicture/')),
                ('user_type', models.CharField(default='mentee', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentormentee.mentorprofile')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
