# Generated by Django 5.0.6 on 2024-06-11 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0003_menteeprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=455)),
                ('user_type', models.CharField(default='web_admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
