# Generated by Django 5.0.6 on 2024-06-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0005_alter_webadminprofile_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentormentee.mentorprofile'),
        ),
    ]
