# Generated by Django 5.0.6 on 2024-06-22 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0006_alter_menteeprofile_mentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=355)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing/InProgress'), ('completed', 'Completed')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_name', to=settings.AUTH_USER_MODEL)),
                ('mentor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
