# Generated by Django 5.0.6 on 2024-06-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0007_menteequery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteequery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing/InProgress'), ('completed', 'Completed')], default='pending', max_length=255),
        ),
    ]
