# Generated by Django 5.0.6 on 2024-06-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0008_alter_menteequery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mentorProfilePicture/'),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='menteeProfilePicture/'),
        ),
    ]
