# Generated by Django 5.0.6 on 2024-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0011_alter_mentorprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
