# Generated by Django 5.0.6 on 2024-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0012_menteeprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='webadminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
