# Generated by Django 5.0.6 on 2024-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0013_webadminprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='dob',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
