# Generated by Django 5.0.6 on 2024-06-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0014_menteeprofile_city_menteeprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webadminprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webadminprofile',
            name='dob',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webadminprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webadminprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webadminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='webAdminProfilePicture/'),
        ),
        migrations.AddField(
            model_name='webadminprofile',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
