# Generated by Django 5.0.6 on 2024-06-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentormentee', '0016_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_type_notification',
            new_name='user_notification_type',
        ),
    ]
